#!/usr/bin/env python3
"""Regenerate explicitly synthetic DEMO output; never query accounts or live files."""
import argparse
import json
from pathlib import Path
from normalize_activity import normalize_all
from build_time_blocks import build_time_blocks
from build_timesheet import build_entries
from prepare_ai_input import prepare_activity_input
from save_timesheet import save_timesheet
from collect_token_usage import update_csv
from atomic_storage import atomic_write
ROOT=Path(__file__).resolve().parent.parent
DATE='2026-10-07'


def build_demo(directory):
    directory=Path(directory)
    commits=[{'hash':'synthetic-commit-001','author':'Synthetic Author','repository':'demo/work',
              'timestamp':DATE+'T10:45:00+07:00','message':'DEMO-1 Fix validation'}]
    prs=[{'id':7,'title':'DEMO-1 Validation','repository':repo,'events':[{'action':'reviewed','actor':'synthetic-user','timestamp':DATE+'T09:45:00+07:00'}]}
         for repo in ('demo-one/work','demo-two/work')]
    events=[{'event_id':'synthetic-a','calendar_id':'synthetic-calendar','source':'synthetic',
             'title':'Synthetic meeting A','start':DATE+'T09:00:00+07:00','end':DATE+'T10:00:00+07:00'},
            {'event_id':'synthetic-b','calendar_id':'synthetic-calendar','source':'synthetic',
             'title':'Synthetic meeting B','start':DATE+'T09:30:00+07:00','end':DATE+'T10:30:00+07:00'}]
    normalized=normalize_all(DATE,commits,prs,events)
    review=[]; blocks=build_time_blocks(normalized,unassigned_activity=review)
    collection={'status':'demo','sources':{name:{'status':'success','mode':'fixture','count':len(items)}
        for name,items in [('git',commits),('pull_requests',prs),('calendar',events)]},
        'token_usage':{'status':'synthetic_example','reason':'Example counts are fabricated demo metrics, not measured usage'}}
    rows=build_entries(blocks)
    for row in rows: row['collection']=collection
    result=save_timesheet(rows,directory,target_date=DATE,collection_status='demo',collection_manifest=collection,
        unassigned_activity=review,calendar_context=[],extra_files={directory/'ai-input.json':json.dumps(prepare_activity_input(blocks,review),indent=2),
        directory/'normalized.json':json.dumps(normalized,indent=2)})
    update_csv(directory/'synthetic-token-usage.csv',[{'date':DATE,'session_id':'synthetic-demo/v1',
        'input_tokens':100,'output_tokens':20,'cache_tokens':5,'total_tokens':125,
        'notes':json.dumps({'source':'synthetic','scope':'fabricated_demo_numbers_not_measurement'})}])
    atomic_write(directory/'README.md','# Synthetic DEMO\n\nGenerated by scripts/build_demo.py. Every account, commit, PR, meeting and token count is synthetic.\nScheduled attendance is unconfirmed; estimated intervals are proposals. No measured work or token saving is claimed.\n')
    return result


def main():
    parser=argparse.ArgumentParser(description=__doc__); parser.add_argument('--output-dir',default=str(ROOT/'examples/synthetic'))
    args=parser.parse_args(); print(json.dumps(build_demo(args.output_dir),indent=2))


if __name__=='__main__': main()
